# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/
- id: tk-fmt
  name: Tanka fmt
  description: Format Jsonnet code with Tanka 
  entry: hooks/tanka-fmt.sh
  language: script
  require_serial: true

